# Generated by Django 4.1.2 on 2022-11-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0002_rename_plano_id_empresa_plano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='expectativas',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workeApp.plano'),
        ),
    ]
