# Generated by Django 4.1.2 on 2022-12-07 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workeApp.plano'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exercicio_realizado',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='exercicio_usuario',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expectativas',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='peso_usuario',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='plano',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usuario_grupo',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
