# Generated by Django 4.1.3 on 2023-01-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0005_alter_empresa_data_criacao_alter_empresa_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workeApp.empresa'),
        ),
    ]
