# Generated by Django 4.1.3 on 2023-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0007_alter_usuario_altura_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
