# Generated by Django 4.1.3 on 2023-02-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0009_usuario_data_ultimo_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workeApp.empresa'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='qtd_participantes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='senha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
