# Generated by Django 4.2 on 2023-05-02 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workeApp', '0020_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='sequencia',
            field=models.IntegerField(default=0),
        ),
    ]
